### PR TITLE
Fixed bug with incorrectly named setter and getter for 'choice'

### PR DESCRIPTION
**Pull request by jasonpranevicius**

### CODE REVIEW

**Comment by sascha-egerer** [comment]
The getters and setters are named correctly! What's your point?

**Comment by jasonpranevicius** [comment]
The property is called choice, not choices, so when attempting to set choices by getting the property Def name it fails

**Comment by sascha-egerer** [comment]
Ah ok now i get it. But i would keep it as `choices` and change the calls to that function instead because it is a list and not a single value.

**Comment by sascha-egerer** [comment]
Fixed in #17

**Pull request closed without merging**
