### PR TITLE
Make deleteObject work with alfresco

### PR DESCRIPTION
**Pull request by guthypeter**

### CODE REVIEW

**Comment by guthypeter** [comment]
See https://tools.oasis-open.org/version-control/browse/wsvn/cmis/trunk/cmis-v1.1/examples/browser/deleteObject-request.log?sc=1 for example

**Comment by dkd-dobberkau** [comment]
Let me find someone else to verify this request.

**Comment by dkd-dobberkau** [comment]
@sascha-egerer or @ksjogo  can you advise me here?

**Comment by NamelessCoder** [comment]
This looks reasonable and is in line with other changes I did previously to compile arrays instead of modifying a (GET) query. It needs testing of course, but the change itself looks fine.

**Pull request merged**
