### PR TITLE
Disable exceptions from 32bit php integer/double conversions

### PR DESCRIPTION
**Pull request by ksjogo**
#13

Unsure about all implications on 32-bit with this.
Should not change anything on 64-bit.
units and examples are running and transmitting int values.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
@MatthewReed Would you mind testing this one on a real-world setup (even better if your Alfresco was manually compiled as 32bit). As @ksjogo mentions we ignore the conversion problems on 32bit platforms and post the raw values instead - the examples test runs but I'm not sure if this would cause problems on the Alfresco side if it is also 32bit (failing in a similar way to how PHP fails, meaning we would have moved the problem but not really fixed it). That's one case I haven't been able to test properly.

Another issue is reporting/logging that the conversion is skipped, I could easily imagine confusion if for example a custom model is built and receives unexpected data types from the client - currently there would be no explanation for it. Since this does break the CMIS standard I think we should be at least logging it or triggering a NOTICE.

**Comment by MatthewReed** [comment]
I apologize but unfortunately I don't have access to development machine and real world examples I used anymore.
You could try and forward your needs to gbravaccini@techngym.com but I don't know wether that company is interested in carrying on a 32bit environment development.

Best Regards
Matteo Rossi

----Messaggio originale----

Da: Claus Due notifications@github.com

Data: 12/05/2016 13.06

A: "dkd/php-cmis-client"php-cmis-client@noreply.github.com

Cc: "MatthewReed"orionerossi@libero.it, "Mention"mention@noreply.github.com

Ogg: Re: [dkd/php-cmis-client] Disable exceptions from 32bit php integer/double conversions (#21)

@MatthewReed Would you mind testing this one on a real-world setup (even better if your Alfresco was manually compiled as 32bit). As @ksjogo mentions we ignore the conversion problems on 32bit platforms and post the raw values instead - the examples test runs but I'm not sure if this would cause problems on the Alfresco side if it is also 32bit (failing in a similar way to how PHP fails, meaning we would have moved the problem but not really fixed it). That's one case I haven't been able to test properly.

Another issue is reporting/logging that the conversion is skipped, I could easily imagine confusion if for example a custom model is built and receives unexpected data types from the client - currently there would be no explanation for it. Since this does break the CMIS standard I think we should be at least logging it or triggering a NOTICE.

**Comment by ksjogo** [comment]
Seems like 32-bit gnu/linux is not supported officially (with installers) anymore.
Added a notice that it should work in the README.

**Comment by NamelessCoder** [comment]
I am fine with this. It's true that 32 bit is not officially supported (which means we don't necessarily have to either) but on a side note, as far as I've read it _is_ possible to compile 32bit versions of Alfresco and possibly other CMIS compatible software. If we come across one such setup that fails we can take it from there and ask the reporter for possible alternative types we can send.

I also recommend that we consider usage with 32 bit an edge case in the _client_ library, but this isn't exactly a decision we could/should do "because Alfresco does it" - since we support every CMIS-compatible service, not just Alfresco. We can discuss that in more detail if needed :)

**Comment by ksjogo** [comment]
Sure, it should not only be related to Alfresco. Next step on my side will be checking the whole implementation against Sharepoint. (in general, not 32-bit).

**Pull request merged**
